# Generated by Django 3.1.5 on 2021-12-09 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_uid', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('PAID', 'paid'), ('CANCELED', 'canceled')], max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
