# Generated by Django 3.1.5 on 2022-01-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220112_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='rentalPrice',
            new_name='price',
        ),
    ]
