# Generated by Django 3.1.5 on 2021-12-09 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=80)),
                ('registration_number', models.CharField(max_length=80)),
                ('power', models.IntegerField()),
                ('price', models.IntegerField()),
                ('car_type', models.CharField(choices=[('SEDAN', 'sedan'), ('SUV', 'SUV'), ('MINIVAN', 'MINIVAN'), ('ROADSTER', 'ROADSTER')], max_length=20)),
                ('availability', models.BooleanField()),
            ],
        ),
    ]
