# Generated by Django 3.1.5 on 2021-12-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211209_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
