# Generated by Django 3.1.5 on 2022-01-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_car_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='registration_number',
            new_name='registrationNumber',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_type',
        ),
        migrations.AddField(
            model_name='car',
            name='carType',
            field=models.CharField(choices=[('SEDAN', 'sedan'), ('SUV', 'suv'), ('MINIVAN', 'minivan'), ('ROADSTER', 'roadster')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
