# Generated by Django 3.1.5 on 2022-01-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220112_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='carUID',
            new_name='carUid',
        ),
    ]
