# Generated by Django 3.1.5 on 2022-01-09 00:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rentalUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80)),
                ('payment_uid', models.UUIDField(default=uuid.uuid4)),
                ('car_uid', models.UUIDField(default=uuid.uuid4)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('FINISHED', 'FINISHED'), ('CANCELED', 'CANCELED')], max_length=20)),
            ],
        ),
    ]
