# Generated by Django 3.1.5 on 2022-01-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='car_uid',
            new_name='carUid',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='date_from',
            new_name='dateFrom',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='date_to',
            new_name='dateTo',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='payment_uid',
            new_name='paymentUid',
        ),
    ]
